cmd/charmcmd: Allow multiple users in list.
juju/charmstore-client pull request #171
Opened 2018-07-19 14:59 UTC by fabricematrat

2018-07-19 15:14 UTC, rogpeppe requested changes
LGTM modulo the dependency issues and a couple of minor suggestions, thanks.

2018-07-19 15:14 UTC, rogpeppe commented on cmd/charm/charmcmd/list.go
> +	for _, user := range users {
v["owner"] = users

?

Or just:

    v := url.Values{
        "sort": "name,-series",
        "owner": users,
    }

?

2018-07-19 15:14 UTC, rogpeppe commented on cmd/charm/charmcmd/list.go
> +		return errgo.Notef(err, "cannot list for user(s) %s", path)
Why include the whole path here rather than just the users as the message implies?

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +gopkg.in/juju/names.v2	git	54f00845ae470a362430a966fe17f35f8784ac92	2017-11-13T11:20:47Z
This looks like it's gone back in time.

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +gopkg.in/juju/charmrepo.v3	git	1068bda266ca4f268822587b820bf1b4a5438745	2018-06-19T10:58:31Z
This looks like it's gone back in time.

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +gopkg.in/goose.v2	git	4dc44b23a313a8a3e4051e7ee568a954a8cb3385	2018-02-08T12:05:40Z
This looks like it's gone back in time.

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +gopkg.in/httprequest.v1	git	3531529dedf047a744dd77f5262515aefff8cd48	2018-03-19T12:54:57Z
This looks like it's gone back in time.

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +gopkg.in/yaml.v2	git	7f97868eec74b32b0982dd158a51a446d1da7eb5	2018-02-23T19:12:37Z
This looks like it's gone back in time.

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +github.com/juju/testing	git	44801989f0f7f280bd16b58e898ba9337807f147	2018-04-02T13:06:37Z
This looks like it's gone back in time.

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +github.com/juju/utils	git	d18e608d01400189bcda3e2669505cbd30e9dda9	2018-02-07T02:18:10Z
This looks like it's gone back in time.

2018-07-19 15:14 UTC, rogpeppe commented on dependencies.tsv
> +github.com/prometheus/client_golang	git	575f371f7862609249a1be4c9145f429fe065e32	2016-11-24T15:57:32Z
This looks like it's gone back in time.

2018-07-19 15:22 UTC, mhilton reviewed
Code looks fine, but why not fix #11 while you're in the code.

2018-07-25 12:36 UTC, rogpeppe commented
LGTM thanks!

2018-07-25 13:12 UTC, fabricematrat commented
:shipit:

2018-07-25 13:15 UTC, jujugui commented
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

2018-07-25 13:17 UTC, merged