cmd/charmcmd: Better yaml output for resources.
juju/charmstore-client pull request #172
Opened 2018-07-24 14:57 UTC by fabricematrat

2018-07-24 15:17 UTC, rogpeppe requested changes
LGTM but please add a test too, thanks.

2018-07-25 12:30 UTC, fabricematrat commented
https://github.com/juju/charmstore-client/issues/134

2018-07-25 12:39 UTC, rogpeppe approved these changes
LGTM with one minor question, thanks!

2018-07-25 12:39 UTC, rogpeppe commented on cmd/charm/charmcmd/listresources_test.go
> +	c.Check(stdout, qt.Equals, `\- name: someResource
What's the backslash doing there?

2018-07-25 13:22 UTC, fabricematrat commented
:shipit:

2018-07-25 13:24 UTC, jujugui commented
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

2018-07-25 13:26 UTC, merged